"""explainability_foundation

Revision ID: 6d7c08a17fb4
Revises: 20260717_0008
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '6d7c08a17fb4'
down_revision: Union[str, None] = '20260717_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('artifact_storage_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['forecast_model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_reports_report_type'), 'diagnostic_reports', ['report_type'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('model_run_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('method_version', sa.String(length=20), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=False),
    sa.Column('limitations_json', sa.JSON(), nullable=False),
    sa.Column('artifact_checksum', sa.String(length=64), nullable=True),
    sa.Column('artifact_storage_key', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['forecast_model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_explanation_model_type', 'explanations', ['model_run_id', 'explanation_type'], unique=False)
    op.create_index(op.f('ix_explanations_explanation_type'), 'explanations', ['explanation_type'], unique=False)
    op.create_index(op.f('ix_explanations_model_run_id'), 'explanations', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_explanations_prediction_id'), 'explanations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_explanations_tenant_id'), 'explanations', ['tenant_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_run_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=True),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['forecast_model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_model_run_id'), 'scenarios', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_scenarios_tenant_id'), 'scenarios', ['tenant_id'], unique=False)
    # removed unsupported alter column statements
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prepared_datasets_status'), table_name='prepared_datasets')
    op.drop_index(op.f('ix_prepared_datasets_readiness_status'), table_name='prepared_datasets')
    op.drop_index(op.f('ix_scenarios_tenant_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_model_run_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_explanations_tenant_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_prediction_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_model_run_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_explanation_type'), table_name='explanations')
    op.drop_index('ix_explanation_model_type', table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_diagnostic_reports_report_type'), table_name='diagnostic_reports')
    op.drop_table('diagnostic_reports')
    # ### end Alembic commands ###
